local require = GLOBAL.require
local STRINGS = GLOBAL.STRINGS

TUNING.WILDCARD_HEALTH = GetModConfigData("WILDCARD_HEALTH")
TUNING.WILDCARD_SANITY = GetModConfigData("WILDCARD_SANITY")
TUNING.WILDCARD_HUNGER = GetModConfigData("WILDCARD_HUNGER")
TUNING.WILDCARD_DAPPERNESS = GetModConfigData("WILDCARD_DAPPERNESS")
TUNING.WILDCARD_HUNGERDRAIN = GetModConfigData("WILDCARD_HUNGERDRAIN")
TUNING.WILDCARD_DAMAGE = GetModConfigData("WILDCARD_DAMAGE")
TUNING.WILDCARD_MOVESPEED = GetModConfigData("WILDCARD_MOVESPEED")
TUNING.WILDCARD_DIET = GetModConfigData("WILDCARD_DIET")
TUNING.WILDCARD_SHADOWWEAPONBUFF = GetModConfigData("WILDCARD_SHADOWWEAPONBUFF")
TUNING.WILDCARD_INSOMNIA = GetModConfigData("WILDCARD_INSOMNIA")
TUNING.WILDCARD_MONSTER = GetModConfigData("WILDCARD_MONSTER")
TUNING.WILDCARD_BRAINTRAUMA = GetModConfigData("WILDCARD_BRAINTRAUMA")
TUNING.WILDCARD_STAFFSANITY = GetModConfigData("WILDCARD_STAFFSANITY")
TUNING.WILDCARD_LITERACY = GetModConfigData("WILDCARD_LITERACY")
TUNING.WILDCARD_NIGHTLIGHT_THRESHHOLD = GetModConfigData("WILDCARD_NIGHTLIGHT_THRESHHOLD")
TUNING.WILDCARD_FUEL_HUNGERDRAIN = GetModConfigData("WILDCARD_FUEL_HUNGERDRAIN")
TUNING.SHADOWWILDCARD_COST = GetModConfigData("SHADOWWILDCARD_COST")
TUNING.SHADOWWILDCARD_SPEED = GetModConfigData("SHADOWWILDCARD_SPEED")
TUNING.SHADOWWILDCARD_DUELIST_DAMAGE = GetModConfigData("SHADOWWILDCARD_DUELIST_DAMAGE")
TUNING.SHADOWWILDCARD_DUELIST_ATTACKPERIOD = GetModConfigData("SHADOWWILDCARD_DUELIST_ATTACKPERIOD")
TUNING.SHADOWWILDCARD_DUELIST_HEALTH = GetModConfigData("SHADOWWILDCARD_DUELIST_HEALTH")
TUNING.SHADOWWILDCARD_DUELIST_REGEN = GetModConfigData("SHADOWWILDCARD_DUELIST_REGEN")
TUNING.SHADOWWILDCARD_WORKER_HEALTH = GetModConfigData("SHADOWWILDCARD_WORKER_HEALTH")
TUNING.WILDCARD_VOICE = GetModConfigData("WILDCARD_VOICE")
TUNING.WILDCARD_MENTALFATIGUE_TIMER = GetModConfigData("WILDCARD_MENTALFATIGUE_TIMER")
TUNING.WILDCARD_MENTALFATIGUE = GetModConfigData("WILDCARD_MENTALFATIGUE")
TUNING.WILDCARD_RABBIFICATION = GetModConfigData("WILDCARD_RABBIFICATION")
TUNING.WILDCARD_EXTRADROPS = GetModConfigData("WILDCARD_EXTRADROPS")

TUNING.WILDCARD_PORTAL_FX = "maxwell_smoke"




